# Generated by Django 3.2.3 on 2021-05-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Picture', 'verbose_name_plural': 'Pictures'},
        ),
    ]
