# Generated by Django 3.2.3 on 2021-05-15 15:54

from django.db import migrations, models
import django_project.utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='author_photos', validators=[django_project.utils.validators.validate_size, django_project.utils.validators.validate_extension])),
            ],
            options={
                'verbose_name': 'Художник',
                'verbose_name_plural': 'Художники',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Город')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pictures', validators=[django_project.utils.validators.validate_size, django_project.utils.validators.validate_extension])),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
    ]
